
USE NISHANT;
CREATE TABLE JOURNEY(
SNO int(20),COUNTRY varchar(30),CAPITAL varchar(40),CONTINENT varchar(40)
);

INSERT INTO JOURNEY(SNO,COUNTRY,CAPITAL,CONTINENT)
VALUES(01,'RUSSIA','MOSCOW','ASIA'),(02,'CHINA','BEIJING','ASIA'),(03,'AMERICA','WASHINGTON','NORTHAMERICA')
,(04,'JAPAN','TOKYO','ASIA'),(01,'SAUDI','RHIYAD','ASIA'),(02,'GERMENY','BERLIN','EUROPE')
,(03,'INDIA','DELHI','ASIA');
USE NISHANT;
CREATE TABLE CITIES(SNO int(20),COUNTRY varchar(30));
INSERT INTO CITIES(SNO,COUNTRY)
VALUES(01,'AFRICA'),(02,'CHINA'),(02,'INDIA'),(03,'UK'),(08,'NEPAL'),(09,'BANGLADESH'),(11,'SHRILANKA');

SELECT JOURNEY.COUNTRY,CITIES.COUNTRY FROM JOURNEY RIGHT JOIN CITIES
ON JOURNEY.SNO=CITIES.SNO;

